### PR TITLE
Webpack 5 support

### PR DESCRIPTION
**Pull request by dangreen**

### CODE REVIEW

**Comment by dangreen** [comment]
https://github.com/developit/optimize-plugin/issues/17

**Comment by developit** [comment]
This looks good! I'll do a proper review soon (both pr's), but I don't see any issues. I like the setup for testing both Webpack versions.

**Comment by dangreen** [comment]
@developit Hi, how review is going?

**Comment by dangreen** [comment]
@developit ?

**Comment by developit** [comment]
Released as [1.1.0](https://github.com/developit/optimize-plugin/releases/tag/1.1.0) - thanks and sorry about the wait!

**Pull request merged**
