### PR TITLE
Fix extracting polyfills

### PR DESCRIPTION
**Pull request by dangreen**
- Now all tests are going well.
- Some tests modifications to skip logging debug info from babel-preset-modernize

### CODE REVIEW

**Comment by dangreen** [comment]
https://github.com/TrigenSoftware/optimize-plugin/runs/4447617581?check_suite_focus=true

**Comment by dangreen** [comment]
@developit review pls 🙏

**Comment by dangreen** [comment]
@developit ping

**Comment by developit** [comment]
Released in [1.1.0](https://github.com/developit/optimize-plugin/releases/tag/1.1.0).

**Pull request merged**
